Controllers/HobilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models.Entity;
using MvcCv.Models.Sinif;

namespace MvcCv.Controllers
{
    public class HobilerController : Controller
    {
        // GET: Hobiler
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.deger5 = db.TBLINTERESTS.ToList();
            return View(cs);
        }

        [HttpGet]
        public ActionResult YeniHobiler()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniHobiler(TBLINTERESTS p)
        {
            db.TBLINTERESTS.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var hobi = db.TBLINTERESTS.Find(id);
            db.TBLINTERESTS.Remove(hobi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult HobiGetir(int id)
        {
            var veriler = db.TBLINTERESTS.Find(id);
            return View("HobiGetir", veriler);
        }

        public ActionResult Guncelle(TBLINTERESTS p)
        {
            var degerler = db.TBLINTERESTS.Find(p.ID);
            degerler.INTEREST = p.INTEREST;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Hobiler/HobiGetir.cshtml
@model MvcCv.Models.Entity.TBLINTERESTS
@{
    ViewBag.Title = "HobiGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Hobiler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.INTEREST)
        @Html.TextBoxFor(m => m.INTEREST, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">GÜNCELLE</button>
    </div>
}

Views/Hobiler/Index.cshtml
@model MvcCv.Models.Sinif.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>HOBİ</th>
            <th>SİL</th>
            <th>GÜNCELLER</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.deger5)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.INTEREST</td>
            <td>@Html.ActionLink("Sil Butonu", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Emin misiniz?')" })</td>
            <td><a href="/Hobiler/HobiGetir/@x.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
        }
    </tbody>
</table>
<a href="/Hobiler/YeniHobiler/" class="btn btn-info">Yeni Hobi Ekle</a>

Views/Hobiler/YeniHobiler.cshtml
@{
    ViewBag.Title = "YeniHobiler";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Hobiler</label>
            <input type="text" class="form-control" name="INTEREST" />
        </div>
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </form>