Controllers/YeteneklerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models.Entity;
using MvcCv.Models.Sinif;
using PagedList;
using PagedList.Mvc;

namespace MvcCv.Controllers
{
    public class YeteneklerController : Controller
    {
        // GET: Yetenekler
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index(int sayfa=1)
        {
            //Class1 cs = new Class1();
            var degerler = db.TBLSKILLS.ToList().ToPagedList(sayfa,3);
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniYetenek()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniYetenek(TBLSKILLS p)
        {
            db.TBLSKILLS.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var ytnk = db.TBLSKILLS.Find(id);
            db.TBLSKILLS.Remove(ytnk);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YetenekGetir(int id)
        {
            var veriler = db.TBLSKILLS.Find(id);
            return View("YetenekGetir", veriler);
        }

        public ActionResult Guncelle(TBLSKILLS p)
        {
            var degerler = db.TBLSKILLS.Find(p.ID);
            degerler.SKILL = p.SKILL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Yetenekler/Index.cshtml
@using MvcCv.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLSKILLS>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>YETENEKLERİM</th>
            <th>SİL</th>
            <th>GÜNCELLER</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <th>@x.ID</th>
                <td>@x.SKILL</td>
                <td>@Html.ActionLink("Sil", "Sil", new { id = x.ID }, new { @class = "btn btn-warning", onclick = "return confirm('Emin misiniz?')" })</td>
                <td><a href="/Yetenekler/YetenekGetir/@x.ID" class="btn btn-success">Güncelle</a></td>

            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))

<a href="/Yetenekler/YeniYetenek/" class="btn btn-info">Yeni Yetenek Ekle</a>

Views/Yetenekler/YeniYetenek.cshtml
@{
    ViewBag.Title = "YeniYetenek";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Yetenekler</label>
            <input type="text" class="form-control" name="SKILL" />
        </div>
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </form>

Views/Yetenekler/YetenekGetir.cshtml
@model MvcCv.Models.Entity.TBLSKILLS
@{
    ViewBag.Title = "YetenekGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Yetenekler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.SKILL)
        @Html.TextBoxFor(m => m.SKILL, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">GÜNCELLE</button>
    </div>
}