Controllers/EgitimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models.Entity;
using MvcCv.Models.Sinif;

namespace MvcCv.Controllers
{
    public class EgitimController : Controller
    {
        // GET: Egitim
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.deger3 = db.TBLEDUCATION.ToList();
            return View(cs);
        }

        [HttpGet]
        public ActionResult YeniEgitim()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniEgitim(TBLEDUCATION p)
        {
            db.TBLEDUCATION.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var egt = db.TBLEDUCATION.Find(id);
            db.TBLEDUCATION.Remove(egt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EgitimGetir(int id)
        {
            var veriler = db.TBLEDUCATION.Find(id);
            return View("EgitimGetir", veriler);
        }

        public ActionResult Guncelle(TBLEDUCATION p)
        {
            var degerler = db.TBLEDUCATION.Find(p.ID);
            degerler.TITLE = p.TITLE;
            degerler.SUBTITLE = p.SUBTITLE;
            degerler.DEPARTMENT = p.DEPARTMENT;
            degerler.GPA = p.GPA;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Egitim/EgitimGetir.cshtml
@model MvcCv.Models.Entity.TBLEDUCATION
@{
    ViewBag.Title = "EgitimGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Egitim", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.TITLE)
        @Html.TextBoxFor(m => m.TITLE, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.SUBTITLE)
        @Html.TextBoxFor(m => m.SUBTITLE, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.DEPARTMENT)
        @Html.TextBoxFor(m => m.DEPARTMENT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.GPA)
        @Html.TextBoxFor(m => m.GPA, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">GÜNCELLE</button>
    </div>
}

Views/Egitim/Index.cshtml
@model MvcCv.Models.Sinif.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>BAŞLIK</th>
                <th>ALTBAŞLIK</th>
                <th>BÖLÜM</th>
                <th>GNO</th>
                <th>SİL</th>
                <th>GÜNCELLER</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model.deger3)
            {
            <tr>
                <th>@x.ID</th>
                <td>@x.TITLE</td>
                <td>@x.SUBTITLE</td>
                <td>@x.DEPARTMENT</td>
                <td>@x.GPA</td>
                <td><a href="/Egitim/Sil/@x.ID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Egitim/EgitimGetir/@x.ID" class="btn btn-success">Güncelle</a></td>
            </tr>
            }
        </tbody>
    </table>
<a href="/Egitim/YeniEgitim/" class="btn btn-info">Yeni Eğitim Ekle</a>

Views/Egitim/YeniEgitim.cshtml
@{
    ViewBag.Title = "YeniEgitim";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Okul</label>
            <input type="text" class="form-control" name="TITLE" />
        </div>
        <br />
        <div>
            <label>Fakülte - Bilgi</label>
            <input type="text" class="form-control" name="SUBTITLE" />
        </div>
        <br />
        <div>
            <label>Bölüm</label>
            <input type="text" class="form-control" name="DEPARTMENT" />
        </div>
        <br />
        <div>
            <label>Genel Not Ortalaması</label>
            <input type="text" class="form-control" name="GPA" />
        </div>
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </form>