Controllers/IlgilenilenlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models.Entity;
using MvcCv.Models.Sinif;

namespace MvcCv.Controllers
{
    public class IlgilenilenlerController : Controller
    {
        // GET: Ilgilenilenler
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLAWARDS select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.AWARD.Contains(p));
            }

            //Class1 cs = new Class1();
            //cs.deger6 = db.TBLAWARDS.ToList();
            return View(degerler.ToList());
        }

        [HttpGet]
        public ActionResult YeniUzmanlıklar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniUzmanlıklar(TBLAWARDS p)
        {
            db.TBLAWARDS.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var uzman = db.TBLAWARDS.Find(id);
            db.TBLAWARDS.Remove(uzman);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult IlgilenilenlerGetir(int id)
        {
            var veriler = db.TBLAWARDS.Find(id);
            return View("IlgilenilenlerGetir", veriler);
        }

        public ActionResult Guncelle(TBLAWARDS p)
        {
            var degerler = db.TBLAWARDS.Find(p.ID);
            degerler.AWARD = p.AWARD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Ilgilenilenler/IlgilenilenlerGetir.cshtml
@model MvcCv.Models.Entity.TBLAWARDS
@{
    ViewBag.Title = "IlgilenilenlerGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Ilgilenilenler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.AWARD)
        @Html.TextBoxFor(m => m.AWARD, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">GÜNCELLE</button>
    </div>
}

Views/Ilgilenilenler/Index.cshtml
@using MvcCv.Models.Entity
@model List<TBLAWARDS>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Ilgilenilenler", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="ARA" />
    </p>
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>UZMANLIKLAR</th>
            <th>SİL</th>
            <th>GÜNCELLER</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.AWARD</td>
            <td>@Html.ActionLink("Sil", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Emin misiniz?')" })</td>
            <td><a href="/Ilgilenilenler/IlgilenilenlerGetir/@x.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
        }
    </tbody>
</table>
<a href="/Ilgilenilenler/YeniUzmanlıklar/" class="btn btn-info">Yeni Uzmanlık Ekle</a>

Views/Ilgilenilenler/YeniUzmanlıklar.cshtml
@{
    ViewBag.Title = "YeniUzmanlıklar";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Uzmanlıklar</label>
            <input type="text" class="form-control" name="AWARD" />
        </div>
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </form>